# Generated by Django 5.2.6 on 2025-09-09 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_produto_vendedor_alter_dashboard_imagem_venda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
